# Generated by Django 3.2.11 on 2023-02-17 10:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('temp1', '0002_auto_20230217_0325'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='phone_no',
            field=models.IntegerField(),
        ),
    ]
