# Generated by Django 3.2.11 on 2023-02-21 11:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('temp1', '0003_alter_employee_phone_no'),
    ]

    operations = [
        migrations.CreateModel(
            name='otp_verifing',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('otp_sent_mail', models.CharField(max_length=30)),
                ('otp_sent', models.IntegerField()),
            ],
        ),
    ]
